module:
  admin_toolbar: 0
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_browser: 0
  entity_embed: 0
  entity_reference: 0
  field: 0
  field_ui: 0
  file: 0
  file_browser: 0
  file_entity: 0
  filter: 0
  geolocation: 0
  google_analytics: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  layout_plugin: 0
  link: 0
  menu_ui: 0
  metatag: 0
  metatag_google_plus: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  mgm_services: 0
  mgm_tools_blocks: 0
  mgm_tools_display: 0
  mgm_tools_slideshow: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  panels: 0
  path: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  search: 0
  shortcut: 0
  social_media_links: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  zurb_foundation: 0
  mtm_foundation: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
