version: 1.2.0
services:
  - mysql

variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    BLT_DIR: $SOURCE_DIR/vendor/acquia/blt


cde-databases:
  - eemmcdowell
  - deiprofundis

events:
  build:
    steps:
        - setup-env:
            type: script
            script:
              - composer validate --no-check-all --ansi
              - composer install --ansi
              - source ${BLT_DIR}/scripts/pipelines/setup_env
        - setup-app:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/setup_app
        - build-artifact:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/build_artifact
  post-deploy:
    steps:
      # Deploy the build artifact to an on-demand environment,
      # and sync the specified databases.
      - deploy:
          script:
            - pipelines-deploy
            - pipelines-sync-dbs eemmcdowell deiprofundis
  # When a GitHub pull request is merged, this deletes the coresponding ODE.
  pr-merged:
    steps:
      - deploy:
          script:
            - echo "Pull request merged"
            - pipelines-deploy

  # When a GitHub pull request is closed, this deletes the coresponding ODE.
  pr-closed:
    steps:
      - deploy:
          script:
            - echo "Pull request closed"
            - pipelines-deploy
