#uuid: 1db84437-2e3e-4e66-a4ca-81297b83f2f7
langcode: en
status: true
dependencies:
  config:
    - views.view.promoted_items
  module:
    - system
    - views
  theme:
    - mariagwyn
_core:
  default_config_hash: 3YSRKx-AFyudYenCVU_S5jqqzlZpYp5xGxGcu0kW1aI
id: views_block__promoted_items_block_1
theme: mariagwyn
region: banner_top
weight: -6
provider: null
plugin: 'views_block:promoted_items-block_1'
settings:
  id: 'views_block:promoted_items-block_1'
  label: ''
  provider: views
  label_display: '0'
  views_label: ''
  items_per_page: none
visibility:
  request_path:
    id: request_path
    pages: '<front>'
    negate: false
    context_mapping: {  }
