project:
  machine_name: eemmcdowell
  prefix: MGM
  human_name: 'MariaGwyn''s Multisites'
  profile:
    name: standard
    contrib: true
  local:
    protocol: http
    hostname: 'local.${project.machine_name}'
git:
  default_branch: master
  remotes:
    - 'eemmcdowell@svn-6098.prod.hosting.acquia.com:eemmcdowell.git'
drush:
  aliases:
    remote: '${project.machine_name}.prod'
    local: self
    ci: self
  default_alias: '${drush.aliases.local}'
target-hooks:
  frontend-setup:
    dir: '${docroot}'
    command: 'echo ''No frontend setup configured.'''
  frontend-build:
    dir: '${docroot}'
    command: 'echo ''No frontend build configured.'''
  pre-config-import:
    dir: '${docroot}'
    command: 'echo ''No pre-config-import configured.'''
  post-deploy-build:
    dir: '${docroot}'
    command: 'echo ''No post-deploy build configured.'''
  post-setup-build:
    dir: '${docroot}'
    command: 'echo ''No post-setup build configured.'''
  post-deploy:
    dir: '${docroot}'
    command: 'echo ''No post-deploy build configured.'''
import: null
modules:
  local:
    enable: [dblog, devel, field_ui, seckit, views_ui]
    uninstall: [acsf, acquia_connector, dblog, shield]
  ci:
    enable: {  }
    uninstall: [acquia_connector, shield]
  dev:
    enable: [acquia_connector, shield]
    uninstall: {  }
  test:
    enable: [acquia_connector, shield]
    uninstall: [devel, field_ui, views_ui]
  prod:
    enable: [acquia_connector, shield]
    uninstall: [devel, field_ui, views_ui]
  deploy:
    enable: [acquia_connector, shield]
    uninstall: [devel, field_ui, views_ui]
multisite:
  name:
    - default
    - magnoliatreemidwifery.com
    - deiprofundis.org
    - theologytimelines.info
behat:
  paths:
    - '${repo.root}/tests/behat'
phpcs:
  filesets:
    - files.php.tests
    - files.php.custom.themes
    - files.frontend.custom.themes
  haltonerror: true
  haltonwarning: true
cm:
  strategy: features

